### ISSUE TITLE
Allow adding tasks for anywhere

### ISSUE THREAD

**Issue by 12people** [SverrirValgeirsson/Todour#1]
I get ideas for what to do all the time, and I need to be able to add these as quickly as possible to maintain focus on what I'm doing.
I'd really appreciate it if Todour allowed me to hit a keyboard shortcut from anywhere and be able to add a task right away.

This is what keeps me using Todoist, which has this quick add feature: https://support.todoist.com/hc/en-us/articles/115001745265-Task-Quick-Add .

**Comment by SverrirValgeirsson** [comment]
Hi. Thanks for that idea. Never thought of it but I would absolutely find that very useful too.
I have a half working prototype already for it :) Lets see if I get it working ok soon.

**Comment by SverrirValgeirsson** [comment]
If you build the latest one, Ctrl+Alt+t will bring up a quick add. I have yet to make it configurable in settings but it works on both mac and windows.

**Comment by 12people** [comment]
That's great—thank you so much!
I'll probably wait for the compiled version—there isn't a makefile provided and no install instructions, so building it myself seems a bit too complicated for me right now.

**Comment by SverrirValgeirsson** [comment]
Fixed in 2.09
