### ISSUE TITLE
Improved undo support

### ISSUE THREAD

**Issue by scyclops** [SverrirValgeirsson/Todour#10]
Hi - I'm enjoying using Todour but a few times already I've accidentally overwritten a todo and wished there was a way to undo my last change.  Thanks!

**Comment by SverrirValgeirsson** [comment]
Hi. 
Agree that it would be good to have that feature. It's on the list for next release.

**Comment by SverrirValgeirsson** [comment]
Added undo now so it will be in 2.19.
