### ISSUE TITLE
encoding for done.txt wrong

### ISSUE THREAD

**Issue by fuchsmich** [SverrirValgeirsson/Todour#11]
Umlauts in todo.txt work fine but not in done.txt

EDIT: using portable windows version 2.17

**Comment by SverrirValgeirsson** [comment]
Hi. That is interesting, since the done.txt file is handled exactly the same as the todo.txt file (by the same routines). 
I will look into it.

**Comment by fuchsmich** [comment]
Tell me, if you need more information.

**Comment by fuchsmich** [comment]
[This](https://github.com/SverrirValgeirsson/Todour/blob/81a3f84cd3481be5bcbdb9043482b0543b24556b/todotxt.cpp#L53) should be 

        in2.setCodec("UTF-8");

**Comment by SverrirValgeirsson** [comment]
Yes. you are right about that one. Nice little copy paste error..  Thanks

**Comment by SverrirValgeirsson** [comment]
Lets see if this fixes it: 12a858e9318c69bbece312381d50a7625decf6ae
