### ISSUE TITLE
how to compile

### ISSUE THREAD

**Issue by cpdef** [SverrirValgeirsson/Todour#13]
I tried to compile the project on linux using the qtcreator but it failed.
It would be nice to have a compile guide in the Readme.md or install.txt or something

**Comment by SverrirValgeirsson** [comment]
Hi. 
That’s odd. It should only require you to push ”build”.
Did you download the git submodules? 

BR
Sverrir

**Comment by SverrirValgeirsson** [comment]
Added how to build on the README
