### ISSUE TITLE
Not able to run the app

### ISSUE THREAD

**Issue by gaganyadav80** [SverrirValgeirsson/Todour#17]
I have the Linux version and I don't know why but when I double click nothing happens
Also,
```bash
chmod a+x Todour
./Todour        
zsh: no such file or directory: ./Todour
```
When I run the above command it says 'no such file or directory'

Simply typing the command in terminal says 'command not found'
```bash
Todour
zsh: command not found: Todour
```

I also have qt5 installed.

**Comment by SverrirValgeirsson** [comment]
Hi.
Have you tried the solution from #16 ?

**Comment by gaganyadav80** [comment]
I'm on Solus os. It's not a debian based distro

**Comment by SverrirValgeirsson** [comment]
Aha, so you're using the .tar.gz file. A possible issue is that it's compiled against i386 libraries and not x86-64, so you need to have qt installed that is 32-bit (or build from source yourself)

**Comment by SverrirValgeirsson** [comment]
Try this build
[Todour-v2.18.tar.gz](https://github.com/SverrirValgeirsson/Todour/files/4719241/Todour-v2.18.tar.gz)

**Comment by gaganyadav80** [comment]
Thanks a lot. This build worked perfectly.
