### ISSUE TITLE
Portable Mode

### ISSUE THREAD

**Issue by smaragdus** [SverrirValgeirsson/Todour#2]
No matter that I start [Todour](https://nerdur.com/todour-pl/) using the following parameter:

`Todour.exe -portable`

or using the shortcut in program folder:

`Todour-portable`

[Todour](https://github.com/SverrirValgeirsson/Todour) still creates an empty key in Windows registry:

`HKEY_CURRENT_USER\Software\Nerdur\Todour`

In my opinion a truly portable version should not touch Windows registry at all.

**Comment by SverrirValgeirsson** [comment]
Hi. 
I actually didn't check for that, my bad (was only looking for it finding the .ini file). 
I agree this is not how it should behave. Will check it out.

**Comment by SverrirValgeirsson** [comment]
Problem found and fixed. Will push out a 2.11 asap

**Comment by smaragdus** [comment]
@SverrirValgeirsson 
Thanks for the express response and fix.
