### ISSUE TITLE
No version number contained in macOS download

### ISSUE THREAD

**Issue by suschizu** [SverrirValgeirsson/Todour#21]
hello @SverrirValgeirsson - I've noticed that the mac download (https://nerdur.com/Todour-v2.19.dmg) doesn't contain any version number:
 
<img width="360" alt="Screenshot 2021-02-05 at 13 10 28" src="https://user-images.githubusercontent.com/16004333/107032117-92861600-67b3-11eb-9d4d-bf7e07cc6299.png">

the BundleVersion and ShortVersionString keys are missing in the info.plist - should look like that:

```
   <key>CFBundleShortVersionString</key>
    <string>x.x.x</string>
    <key>CFBundleVersion</key>
    <string>x.x.x</string>
```

**Comment by core-code** [comment]
i can confirm the issue.

**Comment by SverrirValgeirsson** [comment]
Hi. I had no idea that was supposed to be there :) (just assuming that the macdeployqt tool in Qt would automatically do all magic needed). I will look into it. Thanks

**Comment by SverrirValgeirsson** [comment]
There. Now this is fixed in my build scripts. The 2.20 (that with some luck should be out tomorrow) will have these in place.

**Comment by core-code** [comment]
awesome, thanks!

**Comment by SverrirValgeirsson** [comment]
2.20 is out and it seems to work. Closing this.
![bild](https://user-images.githubusercontent.com/3577564/111085778-249ede00-8519-11eb-8052-6f6587f78f3d.png)

**Comment by core-code** [comment]
i can confirm this is resolved
