### ISSUE TITLE
Exclude rule doesn't work

### ISSUE THREAD

**Issue by fratt-elca** [SverrirValgeirsson/Todour#22]
I have tasks tagged with `@other`.

If I search for `-@other`, it doesn't return anything. It should return all tasks that don't contain `@other`.

**Comment by SverrirValgeirsson** [comment]
Hi. No, if you do !@other you will hopefully get the results you expect. (-@other will search for a literal match of "-@other").

**Comment by Moonbase59** [comment]
I can confirm this works fine on Linux Mint 20.1 (using »!« as »NOT«).

**Comment by SverrirValgeirsson** [comment]
I will close this as it seems to be working as it should.

**Comment by fratt-elca** [comment]
Fine for me, even though that's not how the CLI behaves : https://github.com/todotxt/todo.txt-cli/blob/master/USAGE.md#list

Thanks!

**Comment by SverrirValgeirsson** [comment]
Never used the CLI so I didn't even think of the option :) I might add support for it later. Not a hard thing to do (and I doubt it breaks anything)

**Comment by SverrirValgeirsson** [comment]
Hi again. Added the option to select whatever symbol you want. Will be in 2.20 :) 

![bild](https://user-images.githubusercontent.com/3577564/111043717-509c5f80-8444-11eb-97e1-9feaef27687d.png)
