### ISSUE TITLE
Todour 2.19 Font issue: Size not saved, editing tasks very difficult

### ISSUE THREAD

**Issue by Moonbase59** [SverrirValgeirsson/Todour#23]
On Linux Mint 20.1, I have increased the system font sizes a little because my laptop screen is quite small at 1920x1080.

Todour doesn’t respect these font sizes (menu and text are *really small*.

When setting the "Font size" to, say, 13, it will increase menu and settings window font sizes, but not save this. Upon next start, the fonts are really small again.

Also, Todour apparently uses the set "font size" for editing the task fields. I have specified larger fonts (Roboto Regular 13pt) for "Active" and "Inactive" and when trying to edit an entry, it shows overlapping fonts, making editing an entry almost impossible.

Example:
![todour-2 19-editing](https://user-images.githubusercontent.com/3706922/109240294-851ee300-77d7-11eb-87f7-1610cacf95d7.png)

**Comment by SverrirValgeirsson** [comment]
Hi. Could some of the font size issues be related to this? https://forums.linuxmint.com/viewtopic.php?t=341716&p=1965330 
Todour is a Qt application and Mint seems to have a separate setting for those.

**Comment by Moonbase59** [comment]
Good tip, thanks! Wasn’t aware of *Qt5 Settings*, actually.

I do have to set the same fonts in Qt5 Settings as I have set in system settings, and had to select the same settings in the Todour font selection, to make it good enough to work for me. 

There are still differences in the overlaid text when editing but not as bad as above shown. I think you use the program’s font setting for display but revert to the system (Qt5) font when editing, that possible?

**Comment by SverrirValgeirsson** [comment]
I also had this in the gtk2 setting in the Qt Settings. But when I set it to Fusion it worked as it should. So I would attribute this to being a Qt bug..

**Comment by Moonbase59** [comment]
You’re right, it has to do with the Qt5 style setting. Never tried before, because I actually liked the default settings. Looks like the inventors of "gtk2" style tried for some fancy "shadow" effect here.

So, thanks for testing and valuable insights. Since it’s not your program’s fault, I’ll close this issue, ok?
