### ISSUE TITLE
Todour 2.19: Copy-pasting PARTS of task entry impossible.

### ISSUE THREAD

**Issue by Moonbase59** [SverrirValgeirsson/Todour#24]
I tried to copy-paste the "due:yyyy-mm-dd" part of a task entry into another entry but Todour apparently then pastes *the whole entry* from which I copied, instead of only the marked part. (Marked part of entry, used Ctrl+C to copy and Ctrl+V to paste.)

**Comment by SverrirValgeirsson** [comment]
That I don't manage to recreate (on windows 10). What operating system are you using? If linux, what WM?

**Comment by SverrirValgeirsson** [comment]
I saw in your previous entry that yoou are using Linux Mint. I will try it out and see if I can find the issue

**Comment by Moonbase59** [comment]
Great, thanks! I’m using Linux Mint 20.1/Cinnamon here, pretty standard install, only font sizes increased from 10pt to 12pt in both Mint and Qt5 settings.

**Comment by SverrirValgeirsson** [comment]
Hi. I tried this and it worked well. I noticed though that Todour was much better behaved if I set the Qt settings to emulate something else than gtk2.  Fusion worked much better and looked better. Could you try out and see if you have the same experience?

**Comment by Moonbase59** [comment]
Thanks for testing! It’s almost unbelievable, but the "gtk2" style really messes things up (see also #25). Set it to "Fusion" and copying parts of an entry works!

Personally, I don’t like "Fusion" much, but I like working things better, so it stays …

Maybe this is a thing to report upstream.

**Comment by SverrirValgeirsson** [comment]
I have tried to find a good place to report this (not spent ages on it.. ) but not found any obvious. I have been thinking of moving the whole app off Qt as a platform as it is a bit limiting, but moving it somewhere else will have other tradeofs (like non-native look and feel always for example). I hope some of the other styles both look better and work better for you (on linux I always use KDE so I guess that's why I never saw this).

**Comment by Moonbase59** [comment]
Well … of course I love "perfect", but I’d say "functionality over look". It does it’s work and thus it’s good enough for me right now … ;-)

Re KDE: I started out with KDE many many years ago but switched to Gnome-based DEs ~10 years ago, so I’ll probably see all the "gnomic" problems. :-)

**Comment by SverrirValgeirsson** [comment]
I will lift the issue if I find a suitable place to report it with the Qt team. 

KDE/Gnome.. Well.. Prefer windowmaker still ;)
