### ISSUE TITLE
Todour 2.19: Does `rec:` require `due:`?

### ISSUE THREAD

**Issue by Moonbase59** [SverrirValgeirsson/Todour#26]
In my `todo.txt`, I have a line

```todo
2021-03-01 Check Todour issues @github rec:1w
```

When trying to click *[ ] Done*, it does nothing (doesn’t get checked, ~~no new entry created~~).

**EDIT:** It actually *does* create new entries in `todo.txt`, with exactly the same content, but never shows the "done" entries until the next refresh.

So my question is: *Is a `due:` date required for `rec:` to work?*

As I understood, from other todo.txt apps, `rec:` should work from a `due:` date if given, otherwise simply use the creation date. It should be ignored (but still be able to be set to "Done") if none of both are given. Am I wrong here?

**EDIT:** The *Markor* app on my Android phone will set this task to "Done" (put an `x 2021-03-01` in front of the line) and also not create a new entry. (Seems `rec:` isn’t yet supported.)

My current Todour settings:
![todour-2 19-settings](https://user-images.githubusercontent.com/3706922/109510587-7c156680-7aa2-11eb-94d7-08462a0d62ca.png)

**Comment by SverrirValgeirsson** [comment]
Cool that you are using these features and coming with feedback and questions. I really appreciate it. 

I have seen both and thus I implemented both. So the t: and the due: will be the base if you have used a '+' sign in rec:. Otherwise it will use the date of today. I made this to be compatible with https://swiftodoapp.com/ when I wrote it as I was using an Iphone at the time. You can find the description in the FAQ on that page or here: https://nerdur.com/todour-2-16/

However, the rec function is not of much use in my implementation without a due: or a t: as those are the values it will update when creating a new item. Else it will, as you have seen, just create a new item with todays creation date. 

Would it be of use to set the creation date according to the rec? Or what would be the alternative way of doing it?

**Comment by Moonbase59** [comment]
Thanks! I always loved the Linux approach of having lots of small "modules", each doing only _one_ thing but do it _correctly_, without much overhead or trying to be the "one does it all", and Tudour just fit the bill. ;-) Btw, I love that you included "b" for "business days" with "rec:"!

Let me think out loud about how "rec:" should/could work:

1. In any case, an entry—be it defective as it may—_must_ be deletable. It can be argued this is possible using the "-" button even if setting it to "Done" isn’t possible.

2. What happens if something is set to "Done" is largely dependent on the settings, i.e. "Add dates to lines", "Respect threshold". Also, it must know if a creation date is present on the line.

3. To make thinking easier, let’s assume "Add dates" and "Respect threshold" are both set, and the line contains a creation date.

4. Also, Todour should be as closely compatible to the original spec and other implementations as possible. You and others have certainly much more experience with other implementations than I do, so some help/testing and corrections of my thoughts are needed (I might be wrongly assuming things).

5. One of the base decisions is: Should we _add_ fields like "due:" to the user’s line in _todo.txt_ if they didn’t exist before? This might be needed for a "rec:" in case no "due:" was given originally and we find a date to base it upon. Also, "rec:" already updates an existing "due:" when setting a task to "Done" and thus creating a new one.

6. Recurrence is based on the completion date (i.e., whenever we hit "Done"). It’s only valid on or after a "t:" date, if given. If we have a "rec:+…", recurrence is based on the "due:" date, if given. (What happens if we have a "rec:+…" and no "due:"? Do nothing or create a "completed" line and a new task that copies the original line?)

   I reckon if we use "rec:+…", we _must_ have at least a "due:" date, and we _can_ have an optional "t:" date.

7. If we only got a "rec:" (without "+"), it must recur based on the completion date (i.e. when we hit "Done").
   - If we also have a "due:" date, it must be updated.
   - If we have no "due:", should we add one for the new task? I’m undecided, it has pros and cons. Maybe this could be a setting? Or it _does_ add a "due:" if "Enable due:" is set in the settings?
   - If we also have a "t:", this must be respected if so set in the settings.
   - I was wrong in my first post, talking about the creation date, since only the point of setting a task to "Done" is important for the next recurrence if using "rec:" without a "+". This can easily be gotten from today’s date and has nothing to do with having a creation date in the file or not.
   - Another question is: Should we do colored "warning" and "late", if …
     - "Enable due" is set in settings, and
     - no "due:" date exists, and
     - a creation date exists on the line?
     This could then be based on the creation date, and must also respect "t:", if existent.

Sorry for the long ramble. Thinking about it, I’d probably:

- Make the addition of a new "due:" field dependent on the "Enable due" setting, and
- implement (7) as good as possible.

Reading: [Todo.txt – Recurring tasks](https://updatenotes.blog/todotxt-recurring-tasks/).

**Comment by SverrirValgeirsson** [comment]
Thanks for the thoughts. 

 I agree that there should be added either a due or t when rec is used. Else the behaviour is very odd. There should be a setting for choosing what to do here.  I will implement something and see how it works.

**Comment by SverrirValgeirsson** [comment]
I am not sure I follow on the color marking. Do you mean having an "implicit due" if the creation date + rec time has passed?

**Comment by SverrirValgeirsson** [comment]
I added a function that adds a due: or a t: to a line using rec: if none of these are there 
![bild](https://user-images.githubusercontent.com/3577564/111044930-b93b0a80-844b-11eb-9522-ccdb3ebb780b.png)

Settings
![bild](https://user-images.githubusercontent.com/3577564/111044940-c5bf6300-844b-11eb-9a54-3adf218d18bc.png)

**Comment by SverrirValgeirsson** [comment]
This is out in the 2.20 that I put up today. Try it out :)

**Comment by Moonbase59** [comment]
> I am not sure I follow on the color marking. Do you mean having an "implicit due" if the creation date + rec time has passed?

Yep, something like that.

I’ll surely try the new version real soon now … ;-)

**Comment by Moonbase59** [comment]
OOPS. Some little problem now with 2.20: It adds `rec:` now instead of `due:`! Care to check?

On 2021-03-24, I added the entry `Test rec:1d` and hit _Done_ twice. See what happened:

![todour-2 20--rec-added](https://user-images.githubusercontent.com/3706922/112295926-ae2a7a80-8c94-11eb-83c4-c668abdb0777.png)

My settings:

![todour-2 20-settings](https://user-images.githubusercontent.com/3706922/112295966-b7b3e280-8c94-11eb-8bd1-359633ce3fe9.png)

**Comment by SverrirValgeirsson** [comment]
Hi. I think the technical term is "whoops.." here :) But yes. I see it and I have fixed it. If you just save your settings once (just open the settings and press ok) it is fixed

**Comment by SverrirValgeirsson** [comment]
Fix comitted in 36c165b33b52ef834417d2eec007dc467295bdf5

**Comment by Moonbase59** [comment]
This worked, thanks a lot!
