### ISSUE TITLE
<<QT::endl; replaced w/ << "QT::endl";

### ISSUE THREAD

**Issue by musclecar289** [SverrirValgeirsson/Todour#28]
Qt compilation error on Ubuntu 20.04.

To fix I replaced `<<QT::endl;` with `<< "QT::endl";` in mainwindow.cpp and todotxt.cpp.

Also needed to install:
```
 sudo apt install qtchooser
 sudo apt install qt5-default
 sudo apt install qtbase5-private-dev
 sudo apt install cmake
 sudo apt install libxcb-keysyms1-dev
```

**Comment by SverrirValgeirsson** [comment]
Hi. That was odd. I will look into it. 
Know that the fix you have done will make the debug prints look weird (rather replace with "\n" for example), but that should be the only problem you will face. 
Anyway, I will check out if I can recreate it. These symbols have been a bit of a mess since the Linux versions of Qt are lagging a bit compared to Mac and Windows, causing some errors like this one. .

**Comment by SverrirValgeirsson** [comment]
I added the dependency information to the README (https://github.com/SverrirValgeirsson/Todour/blob/master/README.md)

**Comment by SverrirValgeirsson** [comment]
Intresting that I get none of these errors when building on Ubuntu 20.04. 
I tried on two different ones. I will close the issuse for now and lets re-open if others report the same issue.

**Comment by thomasoliveira** [comment]
I am trying out Todour, and found the same as @musclecar289 regarding QT::endl.

mainwindow.cpp: In constructor ‘MainWindow::MainWindow(QWidget*)’:
mainwindow.cpp:61:74: error: ‘endl’ is not a member of ‘Qt’

Can this be related to https://bugreports.qt.io/browse/QTBUG-82680 ? 

Using Ubuntu 20, where `sudo apt install qt5-default` installed version 5.12.8.

**Comment by SverrirValgeirsson** [comment]
Hi. 
Interesting, and you are absolutely right. I had some magic hiding this problem in my build (so I have obviously had this problem at some point). 
`sed -i 's/Qt::endl/endl/g' *.cpp` does the trick as you point out above. 

I will add a better solutions before closing this issue

**Comment by SverrirValgeirsson** [comment]
16fa5ea8fac6473013a2d429f7f91af36184107f
