### ISSUE TITLE
How to run the app?

### ISSUE THREAD

**Issue by shmu26** [SverrirValgeirsson/Todour#29]
I installed Todour-v2.20.deb on Kubuntu 20.04. No issues with that. But how do I run it? It doesn't appear in the list of installed programs, bash doesn't recognize the command "todour", and I can't find the installation location.

**Comment by shmu26** [comment]
Okay, I found the file: usr/local/bin/Todour. 
Thanks for the app!

**Comment by SverrirValgeirsson** [comment]
Hi. There is another issue to make the app more discoverable on Linux (adding an icon). I will try to figure out how to do that :) .

Hope you find the app useful
