### ISSUE TITLE
Minimize to Tray

### ISSUE THREAD

**Issue by smaragdus** [SverrirValgeirsson/Todour#3]
I would appreciate if you add an option to minimize/close **Todour** to system tray in settings, check-boxes:

- Minimize to tray
- Close to tray

 If you implement such an option you may add to tray commands- right-click on **Todour** tray icon:

- Open
- Exit

For me such an option would be useful because I use lots of programs and my task bar gets easily cluttered. So I would prefer **Todour** to be hidden in tray.

**Comment by SverrirValgeirsson** [comment]
Hi. Thanks for the suggestion. I've added it to the backlog

**Comment by SverrirValgeirsson** [comment]
Hi. I added a tray icon now. So it will be in the next build. Or if you want to build yourself you can use this tag: c62b7bf1bdf24eb1e1c333cdd1706c9201644929

**Comment by smaragdus** [comment]
@SverrirValgeirsson 

Thank you very much for adding tray support, for me it is essential!

I will wait for the next version.

Regards
