### ISSUE TITLE
Todour 2.20: Showing new version available when it’s not

### ISSUE THREAD

**Issue by Moonbase59** [SverrirValgeirsson/Todour#30]
When Doing a _Help → Check for updates_, it shows a "new version" 2.20 being available in spite of already running version 2.20 (I used the .deb for installing):

![todour-2 20-new-version](https://user-images.githubusercontent.com/3706922/112296906-8daef000-8c95-11eb-8238-8d06bffcdc61.png)

**Comment by SverrirValgeirsson** [comment]
Hi. 
I got the same problem on the mac now, but not windows. Funny. I will check it out, thanks.

**Comment by SverrirValgeirsson** [comment]
The code there made no sense. 
Fixed now in 36c165b33b52ef834417d2eec007dc467295bdf5
