### ISSUE TITLE
Feature: Business days (b) settable: Mon-Fri or Mon-Sat

### ISSUE THREAD

**Issue by Moonbase59** [SverrirValgeirsson/Todour#31]
I just ran across a problem that might affect several countries or different areas of work: Business days are sometimes (most often) Monday thru Friday, sometimes Monday thru Saturday.

Would you consider a program setting for this? Like maybe

Business days: `Mon-Fri` | `Mon-Sat`

**Comment by SverrirValgeirsson** [comment]
A bit late, but yes. I will add this as it should be a quite simple setting.

**Comment by SverrirValgeirsson** [comment]
Finally fixed 4cb839ca450e47e54650f2ae797a5977d790fb64
