### ISSUE TITLE
Updated to vsn 2.2 won't add or edit tasks

### ISSUE THREAD

**Issue by AJNiteOwl** [SverrirValgeirsson/Todour#33]
Recently I updated from vsn 2.06 to latest 2.20 without considering whether there had been any significant changes to todo.txt?

Previously/currently resided in (Users)\Dropbox\todo and checked across PC and Samsung Note 8 using Simpletask which will add or delete tasks but nothing happens in Win 10 vsn 2.20 - can't edit existing, create or delete?

Any thoughts?

**Comment by SverrirValgeirsson** [comment]
Hi. This does ring a bell. I had the same problem but it was that the file had somehow become write protected (the todo.txt). There 
have been no changes in how the files are handled for a very long time so there really shouldn't be any issues with this. (I am running with Dropbox, shared between a mac, windows and an android phone using simpletask and it works nicely.

**Comment by AJNiteOwl** [comment]
Hi Sverrir

 

Thanks for responding, I did some checking on the Simpletask website (MPCJanssen) and it looks like there is an issue with Simpletask no longer being on the Play Store and only available from his website as an update – do you know what version of Simpletask you are using I am using 10.3.0 (found under settings>App info>Simpletask)?  It was downloaded from my old Samsung Note 4 using Samsung Smart Switch.  Most recent one available from his website is vsn 10.9.0

 

However the version of Simpletask that I have works ok – from Simpletask tasks can be added and show up in todo.txt and can be deleted etc.

 

I checked to see if there is a special property that has be checked on todo.txt from Win 10 point of view but no – it says can be opened by Notepad which is correct.

 

I have been having some problems with other applications since last Win 10 update on 23/3/21 when good old MS updated a whole lot of drivers (de-installed a range of Bluetooth speakers) and notice that speakers do not come up as selections in the bottom right of the screen like they use to (use to be able to scroll through available speakers and select ones you wanted to use - headphones, Bose headphones, various Bluetooth paired speakers etc).

 

I am wondering if there is a registry corruption or previous “registered” connections to files (and speakers) have been removed, and not reinstated with Win 10 upgrade.  I hear MS are going to move drivers out of the Program Files and Program Files (x86) folders because they have become bloated and apps take too long to start – who knows……

 

Regards

Andrew

**Comment by SverrirValgeirsson** [comment]
Hi. I have Simpletask 10.9.0. 

Can you try to open a copy of the file with Todour and see if there is any difference? (or just make a new directory and a new todo.txt file and see if it has the same problem).

**Comment by SverrirValgeirsson** [comment]
Close as I am not able to reproduce and no more feedback
