### ISSUE TITLE
Filename of icon files / newicon.ico/png -> todour.ico/png / Fedora RPM package

### ISSUE THREAD

**Issue by d-graef** [SverrirValgeirsson/Todour#37]
I have created a RPM package of Todour for Fedora Linux:

https://copr.fedorainfracloud.org/coprs/dgraef/Todour/

I think it is reasonable to change the filename of the icons:
newicon.ico   -> todour.ico
newicon.png  -> todour.png

With the current filename nobody knows to which application the icons belongs (in the directory where all other app icons are placed on Linux).

I'm not sure if the following dependencies (dependency placed in RPM package) for running Todour are sufficient:
Requires:	qt5-qtbase		>= 5.10
Requires:	qt5-qtbase-gui		>= 5.10
Requires:	xcb-util-keysyms	>= 0.4.0

For building Todour the following dependencies are ok, because Todour can be build successfully on fedorainfracloud.org:
BuildRequires:	gcc
BuildRequires:	gcc-c++
BuildRequires:	qt5-qtbase-devel		>= 5.10
BuildRequires:	qt5-qtbase-private-devel	>= 5.10
BuildRequires:	xcb-util-keysyms-devel		>= 0.4.0

**Comment by SverrirValgeirsson** [comment]
Hi.
I forgot about this, sorry. 
Agree on the naming of the icons. I will do that (I have just done the renaming in my build script for debian/ubuntu before). 
The dependencies I have used for debian/ubuntu are libqt5core5a, libqt5gui5 , libqt5widgets5 , libc6 , libxcb1, libxcb-keysyms1
I am not sure how that translates into RPM packages.

**Comment by SverrirValgeirsson** [comment]
Thanks a lot for making an RPM package btw :)

**Comment by SverrirValgeirsson** [comment]
https://github.com/SverrirValgeirsson/Todour/commit/8ae7fe71d8fd60bd3d076b2e795f9793c4e52681
