### ISSUE TITLE
Quit

### ISSUE THREAD

**Issue by smaragdus** [SverrirValgeirsson/Todour#5]
If 'Tray' is enabled and program window is open in order to exit Todour one needs to send it to tray, then right-click on tray icon and then execute 'Quit' command- 3 clicks. To avoid sending Todour to tray to exit it from tray 'Quit' command you may add 'Quit' command in Menu bar, perhaps under 'Settings':

- File
  - Settings
  - Quit

Thus the user would be able to exit the program from program window when 'Tray' is enabled without the need to send it to tray first. I suppose this will be very easy to be implemented.

**Comment by SverrirValgeirsson** [comment]
Hi. Thanks. That one was easy to do and a good idea. Uploaded the change.

**Comment by smaragdus** [comment]
@SverrirValgeirsson 
Thanks for the express implementation!
