### ISSUE TITLE
prevent KDE logout

### ISSUE THREAD

**Issue by roachsinai** [SverrirValgeirsson/Todour#7]
Todour prevent logout from kde each time.

**Comment by SverrirValgeirsson** [comment]
Hi. Ok, I'll check out if I can re-create that

**Comment by roachsinai** [comment]
Thanks.

**Comment by SverrirValgeirsson** [comment]
Hi. I didn't manage to re-create. The application ended as expected when logging out of KDE.
How do you start the application?

**Comment by roachsinai** [comment]
Maybe cause I choose always show todour icon on system tray setting.

**Comment by roachsinai** [comment]
Found if I choose `show tray` option on Todour settings, it prevent KDE logout.

**Comment by SverrirValgeirsson** [comment]
Hi. Thanks. I got it to do that now as well and found the issue. I will upload a patch soon and a new build. 

BR
/s

**Comment by SverrirValgeirsson** [comment]
commit: 93b5a025a37bd88b1d2d669f4fa7d8dc05b94975
