### ISSUE TITLE
Deb-package should describe all needed dependencies

### ISSUE THREAD

**Issue by N0rbert** [SverrirValgeirsson/Todour#8]
Some user on AskUbuntu downloaded your great application and [have had a problem](https://askubuntu.com/q/1123018/66509) with libraries.

Steps to reproduce:
1. Download deb-package with `wget https://nerdur.com/Todour-v2.16.deb`
1. Install deb-package with `sudo apt install ./Todour-v2.16.deb` on Ubuntu 18.04.2 LTS amd64
1. Try to run the application with `Todour` command.

Expected results:
* deb-package is well prepared, the dependencies are described correctly.

Actual results:
* deb-package is poor prepared, the dependencies should be installed manually with [non-intuitive way](https://askubuntu.com/a/1123045/66509):

```
sudo dpkg --add-architecture i386
sudo apt update
sudo apt install -y libc6:i386 libxcb1:i386 libxcb-keysyms1:i386 libqt5widgets5:i386
```

Also note, that real desktop application should have *.desktop* file with nice-looking icon (it is other issue to be reported).

**Comment by SverrirValgeirsson** [comment]
Hi. 
Thanks for the detailed report.  I sadly didn't reflect on that my only linux machine is 32 bit and thus the packaging of course works nicely there while the rest of the world has moved on... I'll update the packaging with the dependencies you found. The amd64 dependency puzzles me a bit though. There should be none of those afaik.

**Comment by N0rbert** [comment]
Thank you for response.
About amd64 it was a typo. The correct line is:

    sudo apt install -y libc6:i386 libxcb1:i386 libxcb-keysyms1:i386 libqt5widgets5:i386

**Comment by SverrirValgeirsson** [comment]
This is fixed in 2.17 (the architecture is specified as i386 in the .deb file and thus apt-get will install a ton of dependencies of it's not available)

**Comment by jason-mehmel** [comment]
Quick note to say thanks to you both for the fix!

**Comment by SverrirValgeirsson** [comment]
No problem. Good you found the issue and help for fixing it :)

Den 2019-03-11 kl. 16:49, skrev jason-mehmel:
