### ISSUE TITLE
Todour should have nice looking icon and desktop file

### ISSUE THREAD

**Issue by N0rbert** [SverrirValgeirsson/Todour#9]
**Steps to reproduce:**
1. Download and install Todour 2.17 on Ubuntu 18.04 LTS (version does not really matter)

       wget https://nerdur.com/Todour-v2.17.deb
       sudo apt install ./Todour-v2.17.deb
2. Try to find application icon in dash.

**Expected results:**
Todour has nice looking icon and desktop file

**Actual results:**
Todour does not have icon and desktop file, the deb-package consists of one executable file:

```
$ dpkg -L todour 
/.
/usr
/usr/local
/usr/local/bin
/usr/local/bin/Todour
```
So user can call the application only by its executable name (`Todour`).

**Comment by roachsinai** [comment]
Hi, there is already a nice looking ico for todour at Theme [Suru++](https://github.com/gusbemacbe/suru-plus), this [issue](https://github.com/gusbemacbe/suru-plus/issues/98) for more detail.

**Comment by Moonbase59** [comment]
Yes, please. Making it appear the menu world be great, and doing the minimum so tools like `gdebi` can see it "installed" (mine doesn’t).

**Comment by SverrirValgeirsson** [comment]
I am not running a linux desktop an honestly don't know how to do this.
I am guessing it is adding an .desktop file in the archive, but I will have to look for some nice tutorial on the subject (tips on something that you know works are welcome).

**Comment by Moonbase59** [comment]
Unfortunately, this is also over my head—maybe some dev who reads this can help?

I reckon there’s a little more to it, probably following some file structure and/or setting some flags so tools like `dpkg`, `apt`, `Synaptic` will know about installed status, version installed, etc.

**Comment by danfe** [comment]
> Todour does not have icon and desktop file

Icon is included in the source distribution, it is baked into program executable as a resource during the build (common mechanism for Qt applications) and being used e.g. for tray.  What's missing is a call to set it to the application itself:

```patch
@@ -5,6 +5,7 @@ int main(int argc, char *argv[])
 {
     QApplication a(argc, argv);
     MainWindow w;
+    a.setWindowIcon(QIcon(":/icons/newicon.png"));
     w.show();
```

**Comment by SverrirValgeirsson** [comment]
Thanks for the tip. Will try it out as soon as possible (I am currently in a mess with QT5 vs qt6 stuff. I think I will just go back to Qt5 for a while until the Linux distros start shipping Qt6 to not have the code littered with ifdefs.. .. )

**Comment by danfe** [comment]
> I think I will just go back to Qt5 for a while until the Linux distros start shipping Qt6

Yes, sticking to Qt5 would be wise.  Given the situation, it's unclear when we will see Qt6 in the distrubutions (if ever).  We (FreeBSD) had recently switched to KDE-maintained Qt5 packages.

**Comment by SverrirValgeirsson** [comment]
Interestingly, setting the icon on the main window in qtcreator 
![image](https://user-images.githubusercontent.com/3577564/166139403-3bb0f4f3-603b-4666-a887-945e2394f58a.png)
seems to have no effect when using X but the change above did. I would have assumed them to have the same effect. Anyway, this is fixed in next version.
